version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/chi-hello-world"
    schedule:
      interval: "daily"
    target-branch: "master"
    reviewers:
      - "rakateja"
    labels:
      - "go"
      - "card-api"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    reviewers:
      - "rakateja"
    labels:
      - "javascript"
